@url = http://localhost:5044
@text = One Two Three

###
GET {{url}}/api
###
GET {{url}}/api/items
###
GET {{url}}/api/embed?query={{text}}
###
GET {{url}}/api/add?query={{text}}
###
GET {{url}}/api/search?query={{text}}
###